brand:
  name: Start Bootstrap
menu-string: Menu

nav:
  - title: Details
    url: '#details'
  - title: Timeline
    url: '#timeline'
  - title: Researcher
    url: '#team'
  - title: Contact
    url: '#contact'

copyright: Copyright Creative Commons Attribution 4.0 International (CC BY 4.0) 

social-buttons:
  - icon: fa fa-twitter
    url: '#' 
  - icon: fa fa-facebook
    url: '#'
  - icon: fa fa-linkedin
    url: '#'

quicklinks:
  - title: Data and Privacy Policy
    url: 'https://medium.com/api-economy-hacklab/privacy-publication-and-data-policy-79362b988cca'

modal:
  date-string: 'Date: '
  client-string: 'Client: '
  category-string: 'Category: '
  close-icon: 'fa fa-times'
  close-string: 'Close Project'
